### ISSUE TITLE
Transfer governance of 1.5 vaults to dev timelock

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-multisig#634] opened 2022-07-05 19:54 UTC
- graviAura
- bauraBal
- bbb-a-usd
- b20wbtc-80badger

**Comment by dapp-whisperer** [comment] 2022-11-08 17:33
as a standard, all governance roles should be under timelock at a specified time after launch. we already have well-tested pausing to handle emergency situations.

some alternatives to doing the process ourselves:
- governance is timelock for all live products
- governance automatically sets to timelock after X time

in any case, any objection @GalloDaSballo

**Comment by GalloDaSballo** [comment] 2022-11-14 22:50
List of 1.5 vaults can be confirmed via Ninja:
https://badger-ninja.vercel.app/monitor

Am assuming the 2 ETH denominated vaults are being skipped because deprecation

**Comment by GalloDaSballo** [comment] 2022-11-14 22:52
<img width="987" alt="Screenshot 2022-11-14 at 23 51 42" src="https://user-images.githubusercontent.com/13383782/201784673-ee3b04df-d947-42c5-a5c8-24608c5c4594.png">
Addresses can also be confirmed via the registry (pasted for convenience)

```solidity
[0xBA485b556399123261a5F9c95d413B4f93107407,v1.5,3,name=graviAURA,protocol=Aura,behavior=None]
[0x37d9D2C6035b744849C15F1BFEE8F268a20fCBd8,v1.5,3,name=auraBAL,protocol=Aura,behavior=Ecosystem Helper]
[0x63ad745506BD6a3E57F764409A47ed004BEc40b1,v1.5,3,name=BADGER/WBTC,protocol=Aura,behavior=None]
[0x371B7C451858bd88eAf392B383Df8bd7B8955d5a,v1.5,3,name=graviAURA/DIGG/WBTC,protocol=Aura,behavior=None]
```

**Comment by petrovska-petro** [comment] 2022-12-09 12:58
Modified gov in:

```
- Gravitationally Bound AURA
- Badger Sett Aura BAL
- Badger Sett 20WBTC-80BADGER 
- Badger Sett 40WBTC-40DIGG-20graviAURA
```

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7facbc816b80>,
│   'safe_address': '0xB65cef03b9B89f99517643226d76e286ee999e77',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001e400ba485b556399123261a5f9c95d413b4f9310740700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930037d9d2c6035b744849c15f1bfee8f268a20fcbd800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930063ad745506bd6a3e57f764409a47ed004bec40b100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300371b7c451858bd88eaf392b383df8bd7b8955d5a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300000000000000000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 153606,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 1089,
│   '_safe_version': '1.1.1',
│   '_chain_id': None
}
```

**Comment by gosuto-inzasheru** [comment] 2022-12-27 13:01
note: 1089 got rejected

**Comment by petrovska-petro** [comment] 2023-05-23 17:18
Modified gov in:

```
- Gravitationally Bound AURA
- Badger Sett Aura BAL
- Badger Sett 20WBTC-80BADGER 
- Badger Sett 40WBTC-40DIGG-20graviAURA
```

```
{
    'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x127c91af0>,
    'safe_address': '0xB65cef03b9B89f99517643226d76e286ee999e77',
    'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
    'value': 0,
    'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001e400ba485b556399123261a5f9c95d413b4f931074070
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930037
d9d2c6035b744849c15f1bfee8f268a20fcbd800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9
b77f88adf8f8c98d7e33fe601dc57bc08930063ad745506bd6a3e57f764409a47ed004bec40b1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
24ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300371b7c451858bd88eaf392b383df8bd7b8955d5a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300000000000000000000000000000000000000000000000000000000'),
    'operation': 1,
    'safe_tx_gas': 153606,
    'base_gas': 0,
    'gas_price': 0,
    'gas_token': '0x0000000000000000000000000000000000000000',
    'refund_receiver': '0x0000000000000000000000000000000000000000',
    'signatures': b'',
    '_safe_nonce': 1102,
    '_safe_version': '1.1.1',
    '_chain_id': None
}
```

**Comment by sajanrajdev** [comment] 2023-06-14 12:26
@gosuto-inzasheru @petrovska-petro, given the vault's deprecation and the burning of keys in the near future, I think we should close this ticket.

**Closed** 2023-06-20 15:25 UTC
